//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
export class Vehicle {
    public _id: string;
    public image: string;
    public registrationPlate: string;
    public vin: string;
    public year: number;
    public model: string;
    public make: string;
}
